[toolchain]
anchor_version = "1.0.0"

[features]
seeds = true
skip-lint = false

[programs.localnet]
# v7.7 dice — new program-id, side-by-side with v7.5 (78Qv6cy...).
dice = "FMwPuCjkfZXN2MuNJQiUzZC3hnxHcD8mrTuntsqA84XD"
coin_toss = "7r6UstdP6qTFK4HSqU4mFGPGyCVWd3JVjBeafQPyvspH"
dice_roll = "CLpaMPxyu5Up4fuZb1JiY2uzj4s4iYVg9RfQHNFRuzAj"
lucky_wheel = "FzUuegZpKT4BHhzms1eJX7L2f6r3NTxMRexs8uqxtnbf"
prediction_market = "EHf5YLG2p7Wca9nUqJXRB6yATZidrBzJKM4Qj4k1EUvc"

[programs.devnet]
# v7.7 dice — new program-id, side-by-side with v7.5 (78Qv6cy...).
dice = "FMwPuCjkfZXN2MuNJQiUzZC3hnxHcD8mrTuntsqA84XD"
coin_toss = "7r6UstdP6qTFK4HSqU4mFGPGyCVWd3JVjBeafQPyvspH"
dice_roll = "CLpaMPxyu5Up4fuZb1JiY2uzj4s4iYVg9RfQHNFRuzAj"
lucky_wheel = "FzUuegZpKT4BHhzms1eJX7L2f6r3NTxMRexs8uqxtnbf"
prediction_market = "EHf5YLG2p7Wca9nUqJXRB6yATZidrBzJKM4Qj4k1EUvc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000
shutdown_wait = 2000

[test.validator]
bind_address = "127.0.0.1"
