#!/usr/bin/env python3
"""
verify_protocol_compat.py
--------------------------
Phase 3 check #1: Verify that the firmware's CBOR wire-protocol schema and
the coordinator's Rust message type definitions describe the same messages.

Exits 0 if compatible, 1 if mismatched, 2 if inputs are missing/unreadable.

Usage:
    python scripts/verify_protocol_compat.py \
        --firmware-schema firmware/components/dice_protocol/schema.cbor \
        --coordinator-messages coordinator/src/protocol/messages.rs
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


# ─── Expected message field definitions ───────────────────────────────────────
# These are the ground-truth field names and types for each DICE wire message.
# Update this table whenever the protocol evolves.

EXPECTED_MESSAGES: dict[str, dict[str, str]] = {
    "Heartbeat": {
        "node_id": "bytes",      # 33-byte compressed secp256k1 pubkey
        "latency_ms": "uint",
        "uptime_secs": "uint",
        "jobs_completed": "uint",
        "timestamp": "uint",
    },
    "JobAssignment": {
        "request_id": "bytes",   # 32-byte request PDA address
        "round_seq": "uint",
        "deadline_ts": "uint",
    },
    "CommitSubmission": {
        "request_id": "bytes",
        "node_id": "bytes",
        "commit_hash": "bytes",  # SHA-256(entropy)
        "signature": "bytes",    # ECDSA sig over commit_hash
    },
    "RevealSubmission": {
        "request_id": "bytes",
        "node_id": "bytes",
        "entropy": "bytes",      # raw 32-byte entropy
        "signature": "bytes",    # ECDSA sig over entropy
    },
    "RoundResult": {
        "request_id": "bytes",
        "status": "text",        # "finalized" | "failed"
        "randomness": "bytes",   # 32-byte final hash (present if finalized)
    },
}


# ─── CBOR schema parser ───────────────────────────────────────────────────────

def load_cbor_schema(path: Path) -> dict[str, dict[str, str]]:
    """
    Parse the firmware CBOR schema file.

    The schema is a JSON-like file (stored as .cbor but encoded as JSON for
    human-readability in the dev tree) with the structure:
        { "MessageName": { "field": "type", ... }, ... }

    Once the firmware is implemented the schema will be generated by
    firmware/components/dice_protocol/gen_schema.py and committed.
    """
    if not path.exists():
        print(f"[WARN] CBOR schema not found at {path} — treating as empty schema")
        return {}

    try:
        # Try JSON first (dev format)
        return json.loads(path.read_text())
    except (json.JSONDecodeError, UnicodeDecodeError):
        pass

    # Binary CBOR: use the `cbor2` library if available
    try:
        import cbor2  # type: ignore
        with open(path, "rb") as f:
            return cbor2.load(f)
    except ImportError:
        print("[ERROR] cbor2 not installed and schema is binary — run: pip install cbor2")
        sys.exit(2)


# ─── Rust messages.rs parser ──────────────────────────────────────────────────

# Regex patterns for simple Rust struct/enum extraction
_STRUCT_RE  = re.compile(r"pub struct (\w+)\s*\{([^}]+)\}", re.DOTALL)
_FIELD_RE   = re.compile(r"pub\s+(\w+)\s*:\s*([^\s,]+)")

_RUST_TO_PROTO_TYPE: dict[str, str] = {
    "Vec<u8>": "bytes",
    "[u8;32]": "bytes",
    "[u8;33]": "bytes",
    "u8":  "uint",
    "u16": "uint",
    "u32": "uint",
    "u64": "uint",
    "u128": "uint",
    "String": "text",
    "&str":   "text",
    "bool":   "bool",
}


def load_rust_messages(path: Path) -> dict[str, dict[str, str]]:
    """Extract message structs from coordinator/src/protocol/messages.rs."""
    if not path.exists():
        print(f"[WARN] messages.rs not found at {path} — treating as empty")
        return {}

    text = path.read_text(encoding="utf-8")
    messages: dict[str, dict[str, str]] = {}

    for struct_match in _STRUCT_RE.finditer(text):
        name   = struct_match.group(1)
        body   = struct_match.group(2)
        fields: dict[str, str] = {}
        for field_match in _FIELD_RE.finditer(body):
            field_name = field_match.group(1)
            rust_type  = field_match.group(2).strip().rstrip(",")
            proto_type = _RUST_TO_PROTO_TYPE.get(rust_type, rust_type)
            fields[field_name] = proto_type
        if fields:
            messages[name] = fields

    return messages


# ─── Comparison ───────────────────────────────────────────────────────────────

def compare(
    cbor_schema: dict[str, dict[str, str]],
    rust_messages: dict[str, dict[str, str]],
) -> list[str]:
    """Return a list of mismatch descriptions. Empty list = compatible."""
    errors: list[str] = []

    for msg_name, expected_fields in EXPECTED_MESSAGES.items():
        in_cbor = cbor_schema.get(msg_name)
        in_rust = rust_messages.get(msg_name)

        if in_cbor is None and in_rust is None:
            print(f"  [SKIP] {msg_name} — not yet in either schema (stub state)")
            continue

        if in_cbor is None:
            errors.append(f"{msg_name}: present in Rust messages.rs but missing from CBOR schema")
            continue

        if in_rust is None:
            errors.append(f"{msg_name}: present in CBOR schema but missing from Rust messages.rs")
            continue

        # Check fields match
        for field, ftype in expected_fields.items():
            cbor_type = in_cbor.get(field)
            rust_type = in_rust.get(field)

            if cbor_type is None:
                errors.append(f"{msg_name}.{field}: missing from CBOR schema")
            if rust_type is None:
                errors.append(f"{msg_name}.{field}: missing from Rust messages.rs")
            if cbor_type and rust_type and cbor_type != rust_type:
                errors.append(
                    f"{msg_name}.{field}: type mismatch — "
                    f"CBOR={cbor_type}, Rust={rust_type}"
                )

        # Check for unexpected fields in either schema
        for field in in_cbor:
            if field not in expected_fields:
                errors.append(f"{msg_name}.{field}: unexpected field in CBOR schema")
        for field in in_rust:
            if field not in expected_fields:
                errors.append(f"{msg_name}.{field}: unexpected field in Rust messages.rs")

    return errors


# ─── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Verify firmware/coordinator protocol compatibility")
    parser.add_argument("--firmware-schema",      required=True)
    parser.add_argument("--coordinator-messages", required=True)
    args = parser.parse_args()

    firmware_schema_path    = Path(args.firmware_schema)
    coordinator_messages_path = Path(args.coordinator_messages)

    print(f"Loading firmware CBOR schema from: {firmware_schema_path}")
    cbor_schema = load_cbor_schema(firmware_schema_path)

    print(f"Loading coordinator messages from:  {coordinator_messages_path}")
    rust_messages = load_rust_messages(coordinator_messages_path)

    print(f"\nComparing against {len(EXPECTED_MESSAGES)} expected message types...")
    mismatches = compare(cbor_schema, rust_messages)

    if mismatches:
        print(f"\n[FAIL] {len(mismatches)} protocol mismatch(es) found:")
        for m in mismatches:
            print(f"  ✗ {m}")
        sys.exit(1)
    else:
        print("\n[PASS] Protocol schemas are compatible")
        sys.exit(0)


if __name__ == "__main__":
    main()
