"use client"

import { useState } from "react"

const FAQS = [
  {
    q: "How is this different from Switchboard or Pyth Entropy?",
    a: "Switchboard uses oracle VRF keys held by operators; Pyth uses a two-phase entropy scheme. DICE is different on the hardware layer — the random byte is generated by a physical ESP32 TRNG and signed in-chip, so there is no key custody question. The oracle cannot reveal what it doesn't hold.",
  },
  {
    q: "Do I need a DICE token to use the service?",
    a: "No. There is no token. Callers pay 0.002 SOL per request, operators receive SOL directly on round finalization. The only token involved is SOL.",
  },
  {
    q: "What happens if a node goes offline mid-round?",
    a: "Rounds tolerate up to two of six nodes failing. The coordinator picks a new quorum for the next round. Offline nodes are automatically deprioritized for selection.",
  },
  {
    q: "Is the hardware reproducible? Can I audit a node?",
    a: "Yes. The firmware is open-source, the bill of materials is published, and each node is field-provisioned with a unique hardware-signed key. You can verify that a received reveal came from a real device.",
  },
  {
    q: "Can I run my own node?",
    a: "Pre-orders open Q3 2026. A node kit costs $89, earns roughly 70% margin at current devnet volume, and takes ~10 minutes to set up. See the pre-order page.",
  },
  {
    q: "Does DICE work on chains other than Solana?",
    a: "Not today. We chose Solana for the sub-second block times and low transaction cost. EVM support is on the roadmap but not committed.",
  },
]

export function Faq() {
  const [open, setOpen] = useState<number | null>(0)

  return (
    <section className="relative">
      <div className="mx-auto w-full max-w-[1400px] px-4 sm:px-6 lg:px-8 pt-20 md:pt-24 pb-0">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 mb-12">
          <div className="lg:col-span-3">
            <span className="chapter-num">08</span>
            <p className="mt-2 font-mono text-[11px] uppercase tracking-[0.2em] text-muted-foreground">
              faq · beginner
            </p>
          </div>
          <div className="lg:col-span-6 lg:col-start-5">
            <h2 className="font-sans text-3xl md:text-4xl lg:text-5xl tracking-[-0.02em] leading-[1.05] text-foreground">
              Common <span className="italic font-light text-muted-foreground">questions.</span>
            </h2>
          </div>
        </div>

        <div className="border-t border-border">
          {FAQS.map((f, i) => {
            const isOpen = open === i
            return (
              <div key={i} className="border-b border-border">
                <button
                  onClick={() => setOpen(isOpen ? null : i)}
                  className="w-full flex items-baseline justify-between gap-6 py-6 text-left hover:bg-muted/20 transition-colors px-2"
                >
                  <span className="flex items-baseline gap-6">
                    <span className="font-pixel text-[11px] text-muted-foreground/60 w-8">
                      0{i + 1}
                    </span>
                    <span className="font-sans text-lg md:text-xl tracking-[-0.01em] text-foreground">
                      {f.q}
                    </span>
                  </span>
                  <span className="font-mono text-foreground text-lg shrink-0">
                    {isOpen ? "−" : "+"}
                  </span>
                </button>
                {isOpen && (
                  <div className="pl-[68px] pr-12 pb-6 -mt-2 font-mono text-[14px] leading-[1.7] text-muted-foreground max-w-3xl">
                    {f.a}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}

export default Faq
